Repository labs-ruby/homeworks-2021, pull requests merged in 2021-05, with the labels that each got.

#35 [HW-3] Solve 4 tasks
  HW03/vorobyov_egor/index.rb
  HW03/vorobyov_egor/lib/logs_parser.rb
  HW03/vorobyov_egor/lib/parsing_functions.rb
Labels: task1, task2, task4

#46 My hw 03
  HW03/Uladzislau_Kanapliou/Uladzislau_Kanapliou_hw_03_t_01.rb
  HW03/Uladzislau_Kanapliou/Uladzislau_Kanapliou_hw_03_t_02.rb
  HW03/Uladzislau_Kanapliou/Uladzislau_Kanapliou_hw_03_t_03.rb
  HW03/Uladzislau_Kanapliou/Uladzislau_Kanapliou_hw_03_t_04.rb
Labels: task1, task4

#50 My HW03
  HW03/Pavel_Shalyga/pavel_shalyga_hw_03_t_01.rb
  HW03/Pavel_Shalyga/pavel_shalyga_hw_03_t_02.rb
  HW03/Pavel_Shalyga/pavel_shalyga_hw_03_t_03.rb
  HW03/Pavel_Shalyga/pavel_shalyga_hw_03_t_04.rb
Labels: task1, task2

#42 [HW03] Parse log
  HW03/sergey_koleshko/.rubocop.yml
  HW03/sergey_koleshko/sergey_koleshko_hw_03_t_01.rb
  HW03/sergey_koleshko/sergey_koleshko_hw_03_t_02.rb
  HW03/sergey_koleshko/sergey_koleshko_hw_03_t_03.rb
  HW03/sergey_koleshko/sergey_koleshko_hw_03_t_04.rb
Labels: task1, task2, task4

#52 [HW-3] by den_havanski (4_methods_for_logs_processing)
  HW03/Denis_Havanski/den_havanski_hw_03_runner.rb
  HW03/Denis_Havanski/den_havanski_hw_03_t_01.rb
  HW03/Denis_Havanski/den_havanski_hw_03_t_02.rb
  HW03/Denis_Havanski/den_havanski_hw_03_t_03.rb
  HW03/Denis_Havanski/den_havanski_hw_03_t_04.rb
Labels: task1, task2, task4
